#!/bin/sh -xe

export GOOGLE_CLOUD_KEYFILE_JSON="/root/.config/gcloud/legacy_credentials/$CIRCLE_PROJECT_REPONAME@$GOOGLE_PROJECT_ID.iam.gserviceaccount.com/adc.json" # Not sure why?

mv /tmp/provider.tf ./

terraform init -input=false

case "$TERRAFORM_COMMAND" in
    apply)
    	terraform apply -input=false -auto-approve
        ;;
    plan)
    	terraform plan -input=false
        ;;
    *)
        echo 'TERRAFORM_COMMAND must be set!'
        exit 1
esac
